version: 2.1

orbs:
  python: circleci/python@2.0.3

update-pip-poetry: &update-pip-poetry |-
  poetry --version
  pip3 install --upgrade pip
  # Note: When changing poetry version, do multi-file find-replace
  pip3 install --upgrade poetry~=1.8.3
  # Don't put more poetry commands here, they'll use the old version for some reason

jobs:
  build_install_test:
    parameters:
      python-version:
        type: string
    executor:
      name: python/default
      tag: << parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Update Pip and Poetry
          command: *update-pip-poetry
      - run:
          name: Poetry show version
          command: poetry --version
      - run:
          name: Poetry build
          command: poetry build --no-ansi --no-interaction
      - run:
          name: Poetry install
          command: poetry install --no-ansi --no-interaction
      - run:
          name: Install coverage
          command: pip install -U coverage coveralls
      - run:
          name: Run pytest
          command: poetry run coverage run -m pytest tests/
      - run:
          name: Coveralls
          command: coveralls
      - when:
          condition:
            equal: [ "3.8", << parameters.python-version >> ]
          steps:
            - store_artifacts:
                path: dist
            - persist_to_workspace:
                root: .
                paths:
                  - dist
  snap_build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2004
      # lxd fails with 22.04... https://discuss.circleci.com/t/lxd-networking-fails-in-2204-image-not-2004-image/44581
      image: ubuntu-2004:2023.07.1
    steps:
      - checkout
      - run:
          name: apt update
          command: sudo apt update
      - run:
          name: Install snapd
          command: sudo apt install snapd
      - run:
          name: Install lxd
          command: sudo snap install lxd
      - run:
          name: Init lxd
          command: lxd init --auto
      - run:
          name: Install Snapcraft
          command: sudo snap install snapcraft --classic
      - run:
          name: Build Snap
          command: snapcraft --verbose
      - run:
          name: Move .snap file
          command: |
            mkdir snap_dist
            mv *.snap snap_dist/
      - store_artifacts:
          path: snap_dist
      - persist_to_workspace:
          root: .
          paths:
            - snap_dist
  poetry_publish:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - run:
          name: Update Pip and Poetry
          command: *update-pip-poetry
      - run:
          name: Poetry show version
          command: poetry --version
      - attach_workspace:
          at: .
      - run:
          name: Poetry publish
          command: poetry publish -vv --no-ansi --no-interaction --username __token__ --password ${TRACEX_PYPI_TOKEN}
  github_publish:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish GitHub release
          command: |
            VERSION=$(echo ./dist/*.whl | cut -d- -f2)
            ghr -token ${GITHUB_PAT} -username ${CIRCLE_PROJECT_USERNAME} -repository ${CIRCLE_PROJECT_REPONAME} -commitish ${CIRCLE_SHA1} -parallel 1 -b "Automatic release ${VERSION}" ${VERSION} ./dist
  snap_publish:
    machine:
      image: ubuntu-2204:2023.07.2  # https://circleci.com/developer/machine/image/ubuntu-2204
    steps:
      - attach_workspace:
          at: .
      - run:
          name: apt update
          command: sudo apt update
      - run:
          name: Install snapd
          command: sudo apt install snapd
      - run:
          name: Install Snapcraft
          command: sudo snap install snapcraft --classic
      - run:
          name: Snapcraft Upload
          # Requires SNAPCRAFT_STORE_CREDENTIALS
          command: snapcraft upload --verbose --release=stable ./snap_dist/*.snap

tag-filter: &tag-filter
  filters:
    tags:
      only: /^\d+\.\d+\.\d+$/
    branches:
      ignore: /.*/

workflows:
  main-workflow:
    jobs:
      - build_install_test:
          matrix:
            parameters:
              python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - snap_build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - poetry_publish:
          requires:
            - build_install_test
            - snap_build
          <<: *tag-filter
      - github_publish:
          requires:
            - build_install_test
            - snap_build
          <<: *tag-filter
      - snap_publish:
          requires:
            - build_install_test
            - snap_build
          <<: *tag-filter
